---
- name: "Windows VM Provisioning"
  hosts: "{{ target_hosts | default('all') }}"
  any_errors_fatal: true
  gather_facts: false
  connection: local

  vars:
    config_guest_os_type: windows

  roles:
    - role: provisioning/vmware_provisioning
      tags: provision
      when: not (dry_run | default(fa lse) | bool)