---
- name: "vCenter Connectivity Test"
  hosts: "{{ ansible_host | default('all') }}"
  any_errors_fatal: true
  gather_facts: true
  connection: local



  roles:
    - role: provisioning/vcenter_connection
      tags:
        - connectivity
        - always