---

- name: "Check VM Configuration Status"
  hosts: "{{ target_hosts | default('all') }}"
  any_errors_fatal: false
  gather_facts: false
  connection: local

  roles:
    - role: provisioning/vm_validation
      vars:
        validation_mode: "display"
      tags: [validation, status, display]