---
galaxy_info:
  author: Vincent Zamora
  description: VM configuration validation role
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 9
  galaxy_tags:
    - vmware
    - validation
    - system

dependencies:
  - role: provisioning/vcenter_connection
    tags: ['always']